services:
  # Servi√ßo da sua API
  autolog-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT=Development
    container_name: autolog_api
    depends_on:
      - postgresdb
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - autolog_network

  postgresdb:
    image: postgres:16
    container_name: autolog_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # Mantenha os dados persistentes no disco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autolog_network

networks:
  autolog_network:
    driver: bridge

volumes:
  postgres_data:
