services:
  db:
    image: postgres:15-alpine
    container_name: autolog_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Note: NÃ£o expomos a porta 5432 para o mundo, apenas para a rede interna do Docker

  api:
    image: autolog_api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autolog_api
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      #ConnectionStrings__DefaultConnection: "Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      ASPNETCORE_ENVIRONMENT: Production
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      HASH_SALT: ${HASH_SALT}
      HASH_JWT_KEY: ${HASH_JWT_KEY}
    ports:
      - "80:80"

volumes:
  postgres_data:
