services:
  db:
    image: postgres:15-alpine
    container_name: autolog_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autolog_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ASPNETCORE_ENVIRONMENT=Production
    image: autolog_api
    container_name: autolog_api
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - HASH_SALT=${HASH_SALT}
      - HASH_JWT_KEY=${HASH_JWT_KEY}
    ports:
      - "8080:80"
    networks:
      - autolog_network

networks:
  autolog_network:
    driver: bridge

volumes:
  postgres_data:
